jet/equinox

cli/Equinox.Cli/Equinox.Cli.fsproj
cli/Equinox.Cli/Program.fs
samples/Store/Domain/Cart.fs
samples/Store/Domain/Favorites.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Store/Integration/LogIntegration.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox/Equinox.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs

This is a cherry-pick from #42, which finesses the way in which one defines rolling snapshots when using `Equinox.EventStore` in order to unify to the maximum degree possible with how one will specify the equivalent rules in `Equinox.Cosmos` (see `unfolds` in #50)

Tidy ES rolling snapshots and builder

---

src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs

This consists of two elements, as described in #50:
- Move all events into `e` arrays
- take advantage of the reduction of clashing names to apply the following renames:
- `c`ompaction events -> `u`nfolds
- `c`reation date/time -> `t`
- unfold/domain event union case/event type (was `et`, presently `t`): `t` -> `c`(ase)
There is some ugliness that drops off in #48 if we adopt this too

Unify Tip vs Batch formats

---

cli/Equinox.Cli/Program.fs
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosFixtures.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs

This PR moves the Access Strategy from it's present approach of having a special case "Index page" (which was arrived at as a spike impl of a performance improvement for the Favorites test) to a more uniform layout which achieves at least the following objectives
- no special case documents needing to be ignored when propagating to other systems
- both the WIP and normal pages now equally hold events, with no waste
- reduce intrinsic contention when lots of writers are appending to the same stream by confining writes to a single document in the bulk of cases (as opposed to current scheme which always touches N+1 docs to write N events every time)
- reduce Request Charges and roundtrips by having fewer documents in the first instance
- allow competing writers to share the events array, …

Multi-event Batches

---

src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs

This PR adjusts the stream encoding to facilitate being able to efficiently project using the CosmosDb changefeed based solely on the tracking of document insert operations.
This is a pessimization when compared to the scheme before, where the `Tip` isa `Batch` in some cases, but one we're taking for now.
The queries presently explicitly exclude the `-1` document; while this ups the RU cost a little, this is generally compensated for by the fact that unfolds will not travel unnecessary.
It should also be noted that the present scheme also sets `i` to `n` consistently, and leaves `e` as `[]` in the tip branch. This should facilitate treating the Tip as yet another Batch from the point of view of querying where relevant, and also allows us to slot in a projector that can deal with mutations …

Remove Tip isa Batch semantics

---

build.ps1
cli/Equinox.Cli/Program.fs
src/Equinox.Cosmos/Cosmos.fs

This addresses #60, enabling: 
./build -ca
or
dotnet run cli/Equinox.Cli -- initAux -ru 400 cosmos -s <REDACTED> -d equinox-test -c ruben
to also initialize a collection as required by the [presently closed source] Projector.
#64 will (after a `dotnet tool install -g`) reduce the above to:
dotnet equinox initAux -ru 400 cosmos -s <REDACTED> -d equinox-test -c ruben

Add CLI `initAux` command for Cosmos

---

Directory.Build.props
azure-pipelines.yml
build.proj
cli/Equinox.Cli/Equinox.Cli.fsproj

fix https://github.com/jet/equinox/issues/64
- pack `Equinox.Cli` as .NET Tool
- bundle the `net461` executable in the package, in the dir `tools/net461/any`
To test is locally, after `dotnet pack build.proj`
```
dotnet tool install --add-source "bin\nupkg" --tool-path bin2 --version 0.0.1 Equinox.Cli
```
and
```
bin2\eqx --help
```
use `-g` instead of `--tool-path` to install globally
it's inside the nupkg, in the `tools/net461/any` directory

Equinox cli as .net tool package

---

Directory.Build.props
README.md
cli/Equinox.Cli/Equinox.Cli.fsproj
src/Equinox.Codec/Equinox.Codec.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.MemoryStore/Equinox.MemoryStore.fsproj
src/Equinox/Equinox.fsproj

This PR uses [MinVer](https://github.com/adamralph/minver) to compute assembly versions based on tags in the git history.
I've included a `v0.0.0-rc1` tag in here; I intend to squash merge to remove that from the history and then re-add it on the squashed commit
There's a `v0.0.1-rc1` at large, which is on the `cosmos` branch; will do the same squash merge and then apply on master dance when we merge that.
... I needed to push it with `git push origin v0.0.0-rc1` for MinVer to pick it up though
... but it seems to have been cached and hence not picked up. Merging to see if it gets picked up by next PR

Use MinVer to infer package versions

---

Equinox.sln
README.md
build.proj
samples/Infrastructure/Storage.fs
tools/Equinox.Tool/Equinox.Tool.fsproj
tools/Equinox.Tool/Infrastructure/Aggregate.fs
tools/Equinox.Tool/Infrastructure/HttpHelpers.fs
tools/Equinox.Tool/Infrastructure/Infrastructure.fs
tools/Equinox.Tool/Infrastructure/LoadTestRunner.fs
tools/Equinox.Tool/Infrastructure/LocalLoadTestRunner.fs
tools/Equinox.Tool/Infrastructure/Types.fs
tools/Equinox.Tool/Program.fs
tools/Equinox.Tool/StoreClient.fs
tools/Equinox.Tool/Tests.fs
tools/Equinox.Tool/TodoClient.fs

This naming fits a teeny bit better alongside `Equinox.Templates`, and allows us to add other tools ... like Projectors ;)

Rename cli/Equinox.Cli to tools/Equinox.Tool

---

Directory.Build.props
Directory.Build.targets
README.md
azure-pipelines.yml
build.proj
src/Equinox.Codec/Equinox.Codec.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.MemoryStore/Equinox.MemoryStore.fsproj
src/Equinox/Equinox.fsproj
tools/Equinox.Tool/Equinox.Tool.fsproj

This PR, a rerun of #71, integrates [MinVer](https://github.com/adamralph/minver) 
HT: this is based on https://github.com/justeat/JustSaying/pull/465, which @adamralph kindly sent me a link to
To test locally (the Azure Pipelines effectively invokes it this way): `dotnet pack /p:build_pr=46 /p:build_id=1000 build.proj`
TODO

Use MinVer

---

src/Equinox.Codec/Equinox.Codec.fsproj
src/Equinox.Cosmos/Equinox.Cosmos.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.MemoryStore/Equinox.MemoryStore.fsproj
src/Equinox/Equinox.fsproj
tools/Equinox.Tool/Equinox.Tool.fsproj

Minver is currently leaking as a dependency in the eqx libraries, causing compile time errors when referenced from libraries that are using the old project system.

Make minver a private asset

---

src/Equinox.Codec/UnionCodec.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.EventStore/Infrastructure.fs
src/Equinox/Handler.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs

This PR makes various minor changes to simplify the code needed for the C# template, https://github.com/jet/dotnet-templates/pull/5

Tweaks for C# interop

---

src/Equinox.Cosmos/Cosmos.fs
src/Equinox.Cosmos/Equinox.Cosmos.fsproj

In order to reduce friction in integrating with applications, this change reduces the min requirement wrt DocumentDb:
-  `net461`: `Microsoft.Azure.DocumentDB" Version="1.17"`
- `netstandard2.0`: `"Microsoft.Azure.DocumentDB.Core" Version="2.1.3"`

Relax DocumentDb.Client version dependencies

---

DOCUMENTATION.md
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs

This PR has a small code change, facilitating attaching event generation helpers e.g.
```
open Equinox.Cosmos.Core
type EventData with
static member fromT eventType value = EventData.FromUtf8Bytes(eventType, Json.toBytes value)
```
Most importantly, it includes additional docs regarding:
- Architectural overview describing the broad set of use cases being covered
- Code example for `Equinox.Core.Events`, derived from the work of Francisco Garcia

Add explicit Cosmos EventData type

---

samples/Store/Backend/Cart.fs
samples/Store/Backend/Favorites.fs
samples/Store/Backend/SavedForLater.fs
samples/Store/Domain.Tests/FavoritesTests.fs
samples/Store/Domain.Tests/Infrastructure.fs
samples/Store/Domain.Tests/SavedForLaterTests.fs
samples/Store/Domain/Domain.fsproj
samples/Store/Domain/Infrastructure.fs
samples/Store/Domain/InventoryItem.fs
samples/Store/Integration/CodecIntegration.fs
samples/Store/Integration/Infrastructure.fs
samples/Store/Integration/Integration.fsproj
samples/Store/Integration/LogIntegration.fs
samples/TodoBackend/Todo.fs
tests/Equinox.Cosmos.Integration/CosmosFixturesInfrastructure.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs
tests/Equinox.EventStore.Integration/Infrastructure.fs
tests/Equinox.MemoryStore.Integration/Infrastructure.fs
tools/Equinox.Tool/Program.fs
tools/Equinox.Tool/StoreClient.fs
tools/Equinox.Tool/Tests.fs
tools/Equinox.Tool/TodoClient.fs

This PR cleans up the Id Types per #83 using https://github.com/fsprojects/FSharp.UMX

Clean up Identity Types

---

src/Equinox.Projection.Kafka/Equinox.Projection.Kafka.fsproj
src/Equinox.Projection.Kafka/Kafka.fs
tests/Equinox.Projection.Kafka.Integration/KafkaIntegration.fs
tools/Equinox.Tool/Program.fs

This PR updates the `Confluent.Kafka` reference from 0.11.4 to the above.
The core of the changes here are based on [the examples](https://github.com/confluentinc/confluent-kafka-dotnet/tree/master/examples)
Reduction in number of config settings is from a mix of spotting redundancy based on [the docs](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) and in reading the xmldoc for the ConsumerConfig/ClientConfig/ProducerConfig classes in the `Confluent.Kafka` library
_It should be noted that moving to 0.11.5 or 0.11.6 also necessitate similar changes to the shutdown logic (which sometimes can be reduced by changing the number of consumers to 1 in the happy path test)_.

Update Projection to use `Confluent.Kafka.1.0.0-beta2`

---

src/Equinox.Projection.Kafka/Equinox.Projection.Kafka.fsproj
src/Equinox.Projection.Kafka/Kafka.fs
tests/Equinox.Projection.Kafka.Integration/KafkaIntegration.fs

Consumer Monitor and Lag metrics
Based on https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

Consumer Monitor and Lag metrics

---

samples/Store/Integration/CodecIntegration.fs
samples/Tutorial/Todo.fsx
src/Equinox.Cosmos/Cosmos.fs

- Adjusts rules re json rendering in Cosmos to facilitate cases without any elements (which json.net translates to a `null` value)
- Add json rendering integration test cases to illustrate that special casing for string union cases is a separate matter

Handle Nullary cases in Cosmos

---

CHANGELOG.md
samples/Infrastructure/Services.fs
samples/Infrastructure/Storage.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Tutorial/Cosmos.fsx
samples/Tutorial/Todo.fsx
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs

Adds friction per #104 to the `CosmosResolver` API to ensure people have to go out of their way to avoid caching

Remove optionality from Cosmos caching

---

CHANGELOG.md
README.md
samples/Infrastructure/Services.fs
samples/Store/Integration/CodecIntegration.fs
samples/Store/Integration/EventStoreIntegration.fs
samples/Tutorial/Cosmos.fsx
samples/Tutorial/Todo.fsx
samples/Web/Startup.fs
src/Equinox.Codec/Codec.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs
tools/Equinox.Tool/Program.fs

Prompted by #113 (and the imminent 2.0 breaking changes) I'm planning to rename:
- `Equinox.Codec.JsonUtf8.Create()` -> `Equinox.Codec.Custom.Create()`
- `Equinox.Codec.JsonNet.JsonUtf8.Create()` -> `Equinox.Codec.NewtonsoftJson.Json.Create()`
This scheme has the following benefits:
- The `Json` bit makes it clear that you're encoding as Json (in some stores it may make sense to render as protobuf, avro etc.)
- No need to mentally map `JsonNet` to "That must be Json.net"
- `Equinox.Codec.Utf8Json.Json.Create()` from #113 slots in logically (and less messy than it would have been: `Equinox.Codec.Utf8Json.JsonUtf8.Create()`)
- No direct clash with top level namespace `Newtonsoft`
- `Equinox.Codec.SystemTextJson.Json.Create()` slots in for #79
- If a codec plugin supports multiple encodings, …

Generalize Codec factory namespacing

---

CHANGELOG.md
samples/Infrastructure/Storage.fs
src/Equinox.Cosmos.Projection/ChangeFeedProcessor.fs
tools/Equinox.Tool/Program.fs

Addresses a shortcoming of the `Equinox.Cosmos.Projection` API - it's assumed that the source collection and the `aux` collection share a CosmosDb account. (See `eqxetl` template in https://github.com/jet/dotnet-templates)

Allow ChangeFeedProcessor with aux in separate account

---

CHANGELOG.md
src/Equinox.Codec/Codec.fs
src/Equinox.Cosmos.Projection/DocumentParser.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tools/Equinox.Tool/Program.fs

In general, the `Timestamp` is worth having for troubleshooting purposes but should generally not be coupled to in application logic
This PR addresses the need (noted in #116) for this facility wrt the `eqxetl` template in https://github.com/jet/dotnet-templates

Expose Event Timestamp in lower level APIs resolves #116

---

CHANGELOG.md
src/Equinox.Cosmos.Projection/DocumentParser.fs

I'm removing the guard clause which prevents events, if any, in Tip being walked by the`enumEvents` function within a projector.
On reflection, it's not necessary for the 1.x-2.x storage formats of `Equinox.Cosmos` and instead means it's another thing to consider should we arrive at the point where we merge #110

Remove special casing of Tip documents in CFP helpers

---

CHANGELOG.md
src/Equinox.Cosmos.Projection/ChangeFeedProcessor.fs
tools/Equinox.Tool/Program.fs

This PR results from work in the `equinox-sync` template in https://github.com/jet/dotnet-templates/pull/19, consisting of:

CFP cleanup: Switch to manual checkpointing, tidy logging, expose further callback

---

CHANGELOG.md
src/Equinox.Cosmos.Projection/ChangeFeedProcessor.fs
tools/Equinox.Tool/Program.fs

This addresses needs arising from work in https://github.com/jet/dotnet-templates/pull/16 wrt:
1. having the assignment and/or revocation do more than just logging; given the underlying `ChangeFeedObserver` offers `Task`-async, exposes the `assign` and `revoke` Async<unit>` methods (For symmetry with `dispose` (and due to lack of imagination!), the `assign` and `revoke` helpers had not previously been async.)
2. Mapping the `IChangeFeedObserverContext.CheckpointAsync` in `Async` (this is used in various places in the templates)
3. Clarifies and documents the `ingest` protocol (formerly `processBatch`) wrt how it needs to cover
i. Flow control / backpressure - the need to impede the consumption by not returning from `ingest` when there's too much of a backlog
ii. Exception management - the …

Cleanup and clarification of ChangeFeedProcessor naming and asyncness

---

CHANGELOG.md
src/Equinox.Projection/Equinox.Projection.fsproj
src/Equinox.Projection/Infrastructure.fs
src/Equinox.Projection/Projection.fs

This code is extracted from https://github.com/jet/dotnet-templates/pull/16 and addresses the following concerns:
- optimization work to enhance throughput i.e. choosing correct `System.Collections.Concurrent` types!
- detailed logging to aid analysis based on logs alone

Projection Perf/logging enhancements

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs

This PR cleans up the `initaux` indexing behavior with the aim of maximizing efficiency and correctness :-
- removing `DefaultTimeToLive` on order to avoid risk of Lease and/or other documents used by either the present or future versions of the CFP lib being removed (used by an internal alternate projector system; use of that system will now now necessitate applying such configuration manually)
- removing indexing (now turned to `Automatic=false, IndexingMode = None`)

Remove TTLs, indexing from Aux config

---

CHANGELOG.md
src/Equinox.EventStore/EventStore.fs

This code, derived from a fix by @asetda (Aset Dauletbaev) to a downstream version fixes the fact that the gossip-based Discovery profiles don't pick up the `.PreferRandomNode()`/`.PreferSlaveNode()` preference on EventStore's `ConnectionSettings`
There's also a fix for a typo which means that the `PreferSlave` semantics would never have worked even in the `Uri` case (this was not present in the downstream repo)...

Fix EventStore Connection Logic wrt Slave/Random nodes on cluster connections

---

CHANGELOG.md
src/Equinox.Cosmos.Projection/ChangeFeedProcessor.fs

Having the partitionId value be known when an observer is `init`ialized and/or `assign`ed can make client code much cleaner
Also provides a way to prevent the default assign/revoke logging

Tidy ChangeFeedProcessor init/assign signature

---

CHANGELOG.md
samples/Web/Program.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
tools/Equinox.Tool/Program.fs

For symmetry with `Equinox.Cosmos`, this adds a `Sync` API that enables one to do a blind write to a stream without going through the transactional API.
This is used in the implementation of the `EventStoreSink` in https://github.com/jet/dotnet-templates/pull/23 (which uses `Equinox.Projection.Scheduling` to track the stream state).
Includes two minor tidying changes

Add EventStore.Gateway.Sync, Stats, ConflictUnknown actualVersion

---

CHANGELOG.md
src/Equinox.Codec/Codec.fs
src/Equinox.Codec/Equinox.Codec.fsproj

Uses an `ArrayPool` to reduce allocations when using `Equinox.Codec`
- https://adamsitnik.com/Array-Pool/
- http://james.newtonking.com/archive/2015/12/20/json-net-8-0-release-1-allocations-and-bug-fixes
Impl is largely guided by https://stackoverflow.com/questions/55812343/newtonsoft-json-net-jsontextreader-garbage-collector-intensive

Use ArrayPool in json.net Codec

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs

As confirmed by @ealsur in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/491, the answer to https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/issues/142 is that best practice is to define the partition key for the aux collection to be `/id` - this change also means we always define a partion key per new conventions

Use id as partitionKey in aux coll

---

CHANGELOG.md
README.md

Same change is happening in https://github.com/jet/dotnet-templates to reflect that projection is not tied to Equinox, and ease confusion badging everything EQUINOX can bring.
(NB this information will likely eventually move to the propulsion API as part of https://github.com/jet/propulsion/issues/6)

Change env vars from EQUINOX_KAFKA* -> PROPULSION_*

---

CHANGELOG.md
DOCUMENTATION.md
README.md
build.ps1
samples/Infrastructure/Services.fs
samples/Infrastructure/Storage.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/LogIntegration.fs
samples/Tutorial/Cosmos.fsx
samples/Tutorial/Todo.fsx
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.Cosmos/CosmosInternalJson.fs
src/Equinox.MemoryStore/MemoryStore.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosFixtures.fs
tests/Equinox.Cosmos.Integration/CosmosFixturesInfrastructure.fs
tools/Equinox.Tool/Program.fs

Renaming brought forward from #144 in order to reduce knock on effects of renames that will come in the Cosmos V3 SDK timeframe

Microsoft.Azure.Cosmos / V3 anticipatory renames

---

CHANGELOG.md
DOCUMENTATION.md
README.md
samples/Store/Domain/Cart.fs
samples/Store/Domain/ContactPreferences.fs
samples/Store/Domain/Favorites.fs
samples/Store/Domain/SavedForLater.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs

TL;DR magic mode that keeps a rolling state in a single document with the same power and surface API as the normal event-sourced model
See #146 for motivation

Implement Cosmos RollingUnfolds strategy re #146

---

CHANGELOG.md
samples/Tutorial/Cosmos.fsx
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox/Flow.fs
src/Equinox/Interfaces.fs
src/Equinox/Stream.fs

When producing summaries, one often performs a `Query` but need to know the Version in question. While this can be inferred from the underlying events, factors like:
- `Equinox.Cosmos.RollingState` (which has snapshots that get revised, which means event level `Index` value is not meaningful)
- each store has its own way of representing versions etc
complicate matters.
This PR exposes a `Version` alongside the state solely for the `QueryEx` method in order to meet a need of the Summary Projection template (having the change feed triggering the app emitting a summary - knowing the version one read allows one to skip projections based on an older state in the projector)

Expose aggregate Version on Equinox.Stream.QueryEx

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs

@jakzale always said it should be like this; It's hard to disagree when a given micro service only touches a single aggregate and a `BatchingPolicy` is far from one's list of concerns.
Example: `return Context(connection, x.Database, x.Container)`

Add all-in-one Cosmos.Context ctor

---

CHANGELOG.md
samples/Store/Domain/Domain.fsproj
samples/Store/Integration/CodecIntegration.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.Cosmos/Equinox.Cosmos.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.EventStore/EventStore.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs
tests/Equinox.EventStore.Integration/Equinox.EventStore.Integration.fsproj

Update to FsCodec 1.0.0-rc2

---

CHANGELOG.md
samples/Tutorial/AsAt.fsx
samples/Tutorial/Tutorial.fsproj

This example leans on #158 to demonstrate building and snapshotting a running balance state.
@ameier38 has [a tutorial that goes way deeper](https://andrewcmeier.com/bi-temporal-event-sourcing) into this territory
One point of note is that this implementation leans on using the `Index` of the event whereas Andrew's implementation maintains internal serial numbers. IMO representing them internally is generally preferable.

Add AsAt example

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox/Stream.fs

This paves the way for using that as a way to request a `UseCached` re #157

Change Target.AggregateIdEmpty to ResolveOption

---

CHANGELOG.md
samples/Store/Domain/Domain.fsproj
samples/Store/Integration/CodecIntegration.fs
samples/Tutorial/AsAt.fsx
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.Cosmos/Equinox.Cosmos.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.EventStore/EventStore.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs
tests/Equinox.EventStore.Integration/Equinox.EventStore.Integration.fsproj

Resolves #160 
@rajivhost looks like no major rebasing/merge mess in your future based on EventStore.fs changes

Adapt to FsCodec name changes

---

CHANGELOG.md
DOCUMENTATION.md
samples/Store/Backend/Cart.fs
samples/TodoBackend/Todo.fs
samples/Tutorial/Todo.fsx
src/Equinox/Accumulator.fs

While the Decide vs Execute distinction was once part of a naming scheme, Accumulator was the only remaining usage thereof. The `interpret` vs `decide` naming of the parameter is intended to provide an equivalent cue

Accumulator tidying followup to #97

---

samples/Infrastructure/Storage.fs
src/Equinox.Core/Cache.fs
src/Equinox.Core/Equinox.Core.fsproj
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.Cosmos/Equinox.Cosmos.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.EventStore/EventStore.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs

I've finally had some free time to hack something together. Here is the summary of changes:
1) Added to interfaces `ICache` interface (note that it's `async` based). Moved the `CacheEntry` type nearby, changed the Token.supersedes logic to be customizable. Added new `CacheEntryOptions` which is a more abstract way to configure the behavior of cache items (relative/absolute expiration).
2) Removed store-specific cache logic. 
3) Extracted `System.Runtime.Caching` integration into a separate project. The implementation remains the same.
4) Added `Microsoft.Extensions.Caching` implementation. Couldn't find a good way to customize the way it calculates object size (which wasn't terribly slow) so added a way to customize it via constructor parameter.
The distributed cache implementation is …

#145 Define ICache, centralize implementation in Equinox.Core

---

CHANGELOG.md
DOCUMENTATION.md
samples/Store/Backend/Cart.fs
samples/Store/Integration/CartIntegration.fs
src/Equinox.Core/Stream.fs
src/Equinox.Core/Types.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox/Equinox.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

Add ResolveOption.AllowStale #157; Write through EventStore Cache

---

CHANGELOG.md
samples/Infrastructure/Storage.fs
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosFixtures.fs

Addendum to #170, exposing a `CreateClient` which exposes the `DocumentClient`
Intended for use with https://github.com/jet/propulsion/pull/40
@Kelvin4702

Add Cosmos.Connector.CreateClient

---

CHANGELOG.md
samples/Store/Integration/CartIntegration.fs
src/Equinox.Core/Cache.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.EventStore.Integration/EventStoreIntegration.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

`ResolveEx` is not as useful in real world apps as it is within this repo
🤔there may be a better angle of approach too: perhaps an `IResolver` common to all stores can have standard helpers over it

Remove ResolveEx

---

CHANGELOG.md
samples/Infrastructure/Services.fs
samples/Infrastructure/Storage.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Tutorial/Counter.fsx
samples/Tutorial/Favorites.fsx
src/Equinox.MemoryStore/Equinox.MemoryStore.fsproj
src/Equinox.MemoryStore/MemoryStore.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

The current implementation of `MemoryStore` stores the events directly, as supplied, without any transformations being applied. One downside to this is that it does enable multiple 'aggregates' to share the same data but with different event Types (e.g. if one aggregate has a subset of the union cases of another).
This upgrades `MemoryStore` to admit a `codec` parameter, which makes it equivalent in facilities to the other stores, including support for metadata management.
relies on https://github.com/jet/FsCodec/pull/25
related: https://github.com/jet/FsCodec/pull/24

Add Codec support for MemoryStore

---

CHANGELOG.md
README.md
samples/Infrastructure/Storage.fs
src/Equinox.Cosmos/Cosmos.fs
tools/Equinox.Tool/Program.fs
tools/Equinox.Tools.TestHarness/Aggregate.fs

Adds an `eqx dump` command that can be used to inspect the raw [json] data of a specified stream from the console.
- `-vc` will trigger emitting storage logging
- `-v` adds detail to said logging

Add eqx dump cosmos

---

.gitignore
samples/Tutorial/Favorites.fsx

While going through the Document.md and following Favorites.fsx, F# interactive had issues running the code because it did not recognize FSCodec. The missing reference has been added to the top. 
Also, .ionide has been added to .gitignore

Added missing FSCodec reference in Favorites.fsx

---

DOCUMENTATION.md
samples/Store/Backend/Cart.fs

In response to a question, this attempts to clarify why Transact has two overloads by expanding the Command Handling Dos and Donts section.
I'm not sure it's actually better as by definition, good examples of valid mixing Commands and Queries is a very specific and subjective case.

Expand on Query/Interpret/Decide docs

---

src/Equinox.Core/Stream.fs
src/Equinox.Core/Types.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs

This PR adds an optional `compress` argument to the `Resolver`'s `Resolve` method, which defaults to `true`. Setting it to `false` will make it so that the data and metadata payloads of the `Unfold` within the `Tip` are stored in CosmosDB as uncompressed and unencoded.

Tip compression toggle through optional argument

---

CHANGELOG.md
samples/Store/Domain.Tests/CartTests.fs
samples/Store/Domain/Cart.fs
samples/Store/Integration/CartIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

This revises the semantics of the Cart sample aggregate in order to reflect:
- converging with semantics that make sense in a more complete Store sample/template re https://github.com/jet/dotnet-templates/issues/27 arrived at in discussions with @oneilk35 
- reflecting expanded considerations in the real Jet implementation
- convergence with techniques observed in production usage of Equinox

Revise Cart Command handling semantics

---

DOCUMENTATION.md

Some crazies, like myself, prefer to read files in their text editor
rather than in a browser, in which case it helps when lines aren't
1,000,000+ characters long :)
There are a few drive-by for-rendering fixes as well, namely changing:
a) foo
b) bar
...
and
i) foo
ii) bar
...
which are rendered as continuous text (rather than list) by GitHub into
1. foo
2. bar
...
which is rendered as an ordered list.
I also aligned a couple of small tables, but left the others alone for
now (too much work).
Some (example) code lines were also split.

Improve readability of unrendered DOCUMENTATION.md

---

CHANGELOG.md
src/Equinox.EventStore/Equinox.EventStore.fsproj

The next version (`20.6`) brings breaking changes - this will go first to `master`, and then will be cherry-picked onto the `v2` branch

Pin EventStore.Client to [5.0.1,6)

---

CHANGELOG.md
src/Equinox.Core/AsyncBatchingGate.fs
src/Equinox.Core/Equinox.Core.fsproj
tests/Equinox.Cosmos.Integration/AsyncBatchingGateTests.fs
tests/Equinox.Cosmos.Integration/Equinox.Cosmos.Integration.fsproj

Helper primitive that can be used to constrain contention where multiple threads are targeting a single upstream.
The specific need at hand is where multiple threads in a projector are transacting against the same aggregate. In such a case the duelling transactions trigger `Equinox.Cosmos` `Resync` operations / ESDB `WrongExpectedVersion` which increases load for the upstream, in addition to increasing latency due to having to retry.
-----
Like `AsyncCacheCell` (although that's slightly more justifiable given its used in the impl of Equinox.Cosmos), these helpers are generic; the happen to be useful in typical Concurrent Transaction processing work, but are not "part of Equinox". Hosting this in Equinox.Core is thus not a long term plan - ideally these primitives ultimately end up with …

Add AsyncBatchingGate

---

CHANGELOG.md
src/Equinox.Core/AsyncCacheCell.fs
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CacheCellTests.fs

The initial impl of AsyncCacheCell passes the tests and fulfilled the need in the context that it was written (an initialization gating device in `Equinox.Cosmos`)
However the `PeekIsValid` perf tweak is a messy ad-hoc thing, so as precursor to https://github.com/jet/equinox/pull/228 I clarified and simplified the logic

Simplify AsyncCacheCell

---

CHANGELOG.md
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.EventStore/EventStore.fs

Equinox.EventStore 2.x (released from `v2` branch) references EventStore.Client 5.x (see also #223, which pins the upper limit to < 6.x to prevent using 20.x)
Equinox.EventStore 3.x will from now depend on `EventStore.Client` v `>= 20.6`
Note [the `EventStore.Client` API is deprecated from an EventStore perspective](https://eventstore.com/blog/event-store-20.6.0-release/), and there'll likely be an `Equinox.EventStore.Grpc` that uses the new API in due course (WIP: https://github.com/jet/equinox/pull/196)

Update to EventStore.Client >= 20.06

---

CHANGELOG.md
samples/Store/Integration/LogIntegration.fs
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosFixturesInfrastructure.fs

See #226 for impl against master
This code will become 2.3.0-rc1

Cosmos: Add Pruning support

---

src/Equinox.Cosmos/Cosmos.fs

Ports a feature provided in Equinox.Cosmos 2.x's Connector to the equivalent in V3
Relevant article: https://devblogs.microsoft.com/cosmosdb/httpclientfactory-cosmos-db-net-sdk/

Cosmos: Port Connector bypassCertificateValidation to V3

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs

In order to allow applications such as archivers to filter log emissions more cleanly, this PR consolidates logging of Sync outcomes and conflicts encountered during same

Extend sync log

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
tests/Equinox.Cosmos.Integration/Equinox.Cosmos.Integration.fsproj

V3 extends the logic of the stored procedure, primarily wrt #109 
This PR cherry-picks the key diffs to the high level flow from there, in order to simplify future diffing and troubleshooting

Cherry-pick V3 stored proc enhancements

---

CHANGELOG.md
README.md
samples/Infrastructure/Storage.fs
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tests/Equinox.CosmosStore.Integration/CosmosFixturesInfrastructure.fs
tests/Equinox.CosmosStore.Integration/CosmosIntegration.fs
tools/Equinox.Tool/Program.fs

As part of #226, implements automated reading from a secondary/fallback Container in cases when the Primary stream has been pruned re #226 
```
dotnet run -- -VC dump -s LokiDcTransmissions-0 -PU cosmos -m gateway -c thor-loki-pruned -c2 thor-loki-archive
```
replaces #238 which was implemented on top of the Cosmos SDK v4 preview

Primary-Secondary Fallback 

---

DOCUMENTATION.md

Adds a section to documentation.md detailing relevant considerations regarding archival and pruning of events and streams over the lifetime of a system.
Constituent parts of the overall feature:
(eventually: `Equinox.CosmosStore`: Implement events in to make archive storage (and archival process in general) more efficient re #110)

Add tiered stream management docs

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs
tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
tests/Equinox.Cosmos.Integration/JsonConverterTests.fs

Port of @ylibrach's https://github.com/jet/equinox/pull/206 to work with `Newtonsoft.Json`
Enables a `Cosmos.Resolver` to inhibit compressing of Unfolds (Snapshot bodies) stored in Tip by adding `, compressUnfolds=false`
CAUTION: Use with care: readers with older versions of `Equinox.Cosmos` will choke on uncompressed values

Cosmos: Enable uncompressed unfolds

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/JsonConverterTests.fs

Port of @ylibrach's https://github.com/jet/equinox/pull/206 to work with `Newtonsoft.Json`
Enables a `CosmosCategory` to inhibit compressing of Unfolds (Snapshot bodies) stored in Tip by adding `, compressUnfolds=false`
CAUTION: Use with care: readers with older versions of Equinox will choke on uncompressed values

CosmosStore: Enable uncompressed unfolds as in v2 #249

---

CHANGELOG.md
samples/Infrastructure/Storage.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Store/Integration/LogIntegration.fs
samples/Web/Startup.fs
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tests/Equinox.CosmosStore.Integration/CosmosIntegration.fs
tools/Equinox.Tool/Program.fs

Replace/renames/reorganizes the `BatchingPolicy` and `RetryPolicy` constructs in the CosmosStore API with two new elements:
- `TipOptions` - policies regarding how we manage the `Tip` document (only)
- `QueryOptions` - policies regarding the loading of events via CosmosDB queries
This is motivated by:
- having a logical place to add options pertaining to the management of events being retained in Tip in #251
- removing an over-generalization in the V1/2 API design/naming: the notion of there being a 'batch size' measured in events when querying events (which works well for ESDB and SSS, but only applies for CosmosDB if you have a one-event-per-Document schema)
- aligning with the API style that's being used for `Azure.Cosmos` aka the V4 SDK (similar `Options` naming) re #197
- handling …

CosmosStore: BatchingPolicy -> TipOptions + QueryOptions

---

CHANGELOG.md
src/Equinox.Core/Cache.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs

resolves #254 
NOTE when using this, you need to opt out of the db roundtrip (even with a cache hit) by changing calls to `category.Resolve streamName` to `category.Resolve(streamName, Equinox.AllowStale)`

Add CachingStrategy.FixedTimeSpan

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tests/Equinox.CosmosStore.Integration/CosmosIntegration.fs

Straggler work for #247 prompted by #259
Fixes bugs exposed by a guard added in response to a TODO comment in the original implementation
Also exposes a bug that will be addressed in the more generalized implementation of pruning coming in #259

CosmosStore: Fallback test suite extensions+fixes

---

CHANGELOG.md
src/Equinox.Cosmos/Cosmos.fs

Adds a missing `DefaultValueAttribute`, as evidenced by https://github.com/jet/dotnet-templates/commit/72209da1f2435325b6794e09014d8f9073f5ead4#diff-8c764ce44d257e5ae802cde1162c04cecdd6b005c1ebfe0e799415c4f626f2d0R79

Fix compressUnfolds defaulting for C#

---

CHANGELOG.md
tools/Equinox.Tool/Equinox.Tool.fsproj

In order to allow usage of tool where only SDK >= 5 is installed in a given context

Add RollForward for Equinox.Tool

---

CHANGELOG.md
src/Equinox/Decider.fs
src/Equinox/Flow.fs

Cleans `createAttemptsExhaustedException` Decider argument to allow throwing any `Exception`; this had inadvertently been constrained to require it to inherit from `MaxResyncsExhaustedException`

Fix createAttemptsExhaustedException to allow exn

---

CHANGELOG.md
src/Equinox/Decider.fs
src/Equinox/Flow.fs

At present, the `Equinox.Decider` interface only exposes the outgoing `Version`, which means the only way to determine the incoming Version is by indirect means such as:
- checking the `Index` of the freshest event (can be incorrect if an Event that's not in the DU is encountered)
- inferring it based on the post-`Version` passed to the `mapResult` (won't work well with transmute operations or rolling snapshots)
This proposal provides the incoming extended state via a new `TransactEx` API, enabling one to process the value directly.
As this is only for V3, it makes sense to remove `TransactAsyncEx` as both APIs are likely extremely rare, and having 2 mysteriously named functions with complex signatures is rarely better than one.
cc @dharmaturtle

Expose pre-state Version via TransactEx

---

CHANGELOG.md
src/Equinox.Cosmos.Prometheus/CosmosPrometheus.fs

:blush: Didnt correct the namespace when cherry-picking in #267
Fixing so V2 `.Cosmos` and V3 `.CosmosStore` stores can run side-by-side in future

Fix Cosmos.Prometheus namespace

---

CHANGELOG.md
src/Equinox/Equinox.fs
src/Equinox/Flow.fs

Backports #263 i(ncluding removing of `TransactAsyncEx`)

Expose pre-State via TransactEx API

---

CHANGELOG.md
samples/Store/Backend/Favorites.fs
samples/Store/Integration/FavoritesIntegration.fs
src/Equinox.Cosmos/Cosmos.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
src/Equinox/Flow.fs

This addresses a problem at two levels:
- `Equinox.Cosmos` v `2.5.0` can return a Version of `0` when re-reading a stream that
a) uses `AccessStrategy.Unoptimized`
b) uses a cache
- the `Version` field was defined in an ambiguous manner, indicating it was a store-native version field
a) That doesn't make sense for an interface in the `Equinox` package
b) There's a reasonable general way to express it in a neutral way
The fix consists of:
- a doc change for the property
- patching the bug in the corner case that caused the actual issue (will follow up with a V3 edition of this shortly - its likely that the events in Tip impl removed the issue on that side)
- changing the impl of the SSS, ESDB and MemoryStore stores to match the new definition

Consistency changes/fixes for `ISyncContext.Version`

---

CHANGELOG.md
samples/Infrastructure/Storage.fs
samples/Tutorial/AsAt.fsx
samples/Tutorial/Cosmos.fsx
samples/Tutorial/FulfilmentCenter.fsx
src/Equinox.CosmosStore/CosmosStore.fs

The `Cosmos` store on the `/v2` branch has the default connection mode aligned with the underlying Cosmos V2 SDK default mode: Gateway
The fact that this can leave significant perf on the table, and is not aligned with the default in the Cosmos V3 SDK makes this a bad default going forward so taking the hit of breaking it now as we move to V3.

CosmosStore: Flip default Connection mode to Direct

---

CHANGELOG.md
src/Equinox.Cosmos.Prometheus/CosmosPrometheus.fs

This generalizes the `app` metrics-tag to allow one to programmatically add arbitrary tags to the generated metrics.
As a rule, most of this tagging should be managed as config in one's Prometheus ingester; this facility as it is right now is only strictly needed if you're in a constrained environment that does not facilitate doing things the correct way.

Cosmos.Prometheus: Replace app tag with custom tags

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

Reverts overwrite of changes in #281 in #280
Typically, this will not surface as a bug in normal usage as `dotnet-templates` explicitly specifies the `mode`

Fix accidental reversion of #281

---

CHANGELOG.md
DOCUMENTATION.md
samples/Infrastructure/Storage.fs
samples/Tutorial/AsAt.fsx
samples/Tutorial/Cosmos.fsx
samples/Tutorial/FulfilmentCenter.fsx
samples/Tutorial/Todo.fsx
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs

Circles back to changes triggered in #280 based on polishing in https://github.com/jet/dotnet-templates/pull/91
- reintroduce `CosmosStoreConnector` type to avoid leaking curried `member Connect` in `CosmosClientFactory` into normal usage
- intentional breaking changes: reordering of ctor args, hiding `CosmosClientFactory` and removal of `Connect`

Reintroduce CosmosStoreConnector

---

CHANGELOG.md
samples/Store/Domain.Tests/FavoritesTests.fs
samples/Store/Domain/Favorites.fs
samples/Store/Integration/FavoritesIntegration.fs
src/Equinox.MemoryStore/MemoryStore.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

Corrects `MemoryStore`'s computation of the post-`Version` for use by `Equinox.Decider.TransactEx`
Refactors conflict case path to remove ugly use of `Exception` that I once assumed to be unavoidable

MemoryStore: Fix Version for post-context in Equinox.Decider.TransactEx

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs

Following same pattern as established in Propulsion.
Some work (fixing labels, renaming Event->Metric) deferred for #232

Add PropertyTag Literals

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs
tools/Equinox.Tool/Program.fs

Adds an `--autoscale`/`-A` switch to the `eqx` tool to support [autoscaling throughput](https://docs.microsoft.com/en-us/azure/cosmos-db/provision-throughput-autoscale) of Cosmos containers and databases. Specifying this flag causes the `--rus` parameter to be interpreted as "Maximum RU/s" and changes the default value to 4000 RU/s (the minimum MaxRUs value allowed by Cosmos).
There are no changes to existing behavior. The Propulsion tool is also unaffected.
There are breaking changes in the `Equinox.CosmosStore.Core.Initialization.init` function, specifically the `mode` parameter's `Provisioning` type had its `rus` members changed to `Throughput` type. The `initAux` function remains unchanged.
There is no plan to update the Propulsion tool since the minimum RU/s in both Manual and …

Equinox.Tool: Add support for Cosmos Autoscaling

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs

Not sure when this was introduced as yet, but 3.0-specific, and triggers multiple failing tests which went unnoticed due to the absence of a pair of containers for testing

Fix fallback when Tip pruned to no events

---

CHANGELOG.md
DOCUMENTATION.md
README.md
samples/Tutorial/Cosmos.fsx
samples/Tutorial/Todo.fsx
src/Equinox.CosmosStore.Prometheus/CosmosStorePrometheus.fs
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs

Long overdue cleanup in CosmosStore - initial logic was intentionally matching V2 init logic, but it can be clarified now based on:
- support for Autoscale from @belcher-rok 
- the V3 SDK has Database and Container objects where V2 did not

CosmosStore: Cleanup Cosmos calls

---

CHANGELOG.md
tools/Equinox.Tool/Program.fs

Polish eqx dump

---

CHANGELOG.md
azure-pipelines.yml
samples/Store/Integration/LogIntegration.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
tests/Equinox.EventStore.Integration/Infrastructure.fs

- `EventStore/SqlStreamStore`: rename `Equinox.XXXStore.Log.Event` -> `Metric` to match `CosmosStore`
- `SqlStreamStore`: correct internal name to `ssEvt` (was `esEvt`)

EventStore/SqlStreamStore: Log consistency

---

CHANGELOG.md
azure-pipelines.yml
samples/Infrastructure/Services.fs
samples/Store/Domain/Cart.fs
samples/Store/Domain/ContactPreferences.fs
samples/Store/Domain/Domain.fsproj
samples/Store/Domain/Favorites.fs
samples/Store/Domain/Infrastructure.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Tutorial/Gapless.fs
samples/Tutorial/Index.fs
samples/Tutorial/Sequence.fs
samples/Tutorial/Set.fs
samples/Tutorial/Tutorial.fsproj
samples/Tutorial/Upload.fs
src/Equinox.CosmosStore.Prometheus/Equinox.CosmosStore.Prometheus.fsproj
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.CosmosStore/CosmosStoreSerialization.fs
src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
tests/Equinox.CosmosStore.Integration/AccessStrategies.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs
tests/Equinox.CosmosStore.Integration/CosmosIntegration.fs
tests/Equinox.CosmosStore.Integration/JsonConverterTests.fs

Cherry-pick from #197 see #232

CosmosStore: Switch to JsonElement bodies

---

README.md
docker-compose.yml
tests/Equinox.EventStore.Integration/StoreIntegration.fs

Re https://github.com/microsoft/mssql-docker/issues/2#issuecomment-1059819719
Until it's automated and/or the image follows the rest of the world, documents the need to manually do:
```zsh
docker exec -it equinox-mssql /opt/mssql-tools/bin/sqlcmd \
-S localhost -U sa -P "!Passw0rd" \
-Q "CREATE database EQUINOX_TEST_DB"
```

Document MSSQL 2019 Docker Image workaround

---

CHANGELOG.md
tools/Equinox.Tool/Equinox.Tool.fsproj
tools/Equinox.Tool/Program.fs

For some reason, I encountered JSON with `null` values that Newtonsoft.Json choked on when pretty-printing
The code was due a migration anyway, and this resolves the issue

Fix eqx dump handling of null values

---

src/Equinox.Core/Cache.fs
src/Equinox.Core/Caching.fs
src/Equinox.Core/Equinox.Core.fsproj
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs

Prep/cleanup in advance of #196 potentially introducing a third clone of the caching logic into the codebase

Moving Caching logic to central file

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
src/Equinox/Core.fs
src/Equinox/Decider.fs
tools/Equinox.Tool/Program.fs

While this is a generally useful mechanism for any cases where one is try to maintain a series of epochs, the specific driver here is to enable optimization of `Propulsion.DynamoStore.AppendsEpoch`.

Add ISyncContext.StreamEventBytes

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

Modifies initialization of aux collection to take an explicit input representing the cosmos provisioning mode. This change will be used in 'Propulsion.Tool' for supporting autoscale option and 'serverless' cosmos database.

CosmosStore - Extend aux collection initialization

---

src/Equinox.CosmosStore/CosmosStoreSerialization.fs
src/Equinox.DynamoStore/DynamoStore.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs

Adds logic to correctly handle cases where the reader traverses the `TimelineEvent.Data` more than once.
In the typical case, Equinox-controlled loads will only walk the events exactly once [until `isOrigin` stops the search]
However in more exotic cases such as in projection loops, there can be cases (and this issue surfaced as an exception in such logic) where layering is such that filtering layers perform some pre-traversals.
It has been argued by @yreynhout that compression doesn't belong in this layer; certainly its absence would have avoided this specific issue, and I can't say I like the impl having ugly excuses and guards as this PR introduces.
Removing it would at a minimum entail adding some form of content-encoding/content-type to the `ITimelineData` in order for an outer layer …

DynamoStore: Cache decoding of Data/Meta

---

CHANGELOG.md
DOCUMENTATION.md
samples/Infrastructure/Services.fs
samples/Infrastructure/Storage.fs
samples/Store/Domain/ContactPreferences.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/EventStoreIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Tutorial/AsAt.fsx
samples/Tutorial/Cosmos.fsx
samples/Tutorial/FulfilmentCenter.fsx
samples/Tutorial/Gapless.fs
samples/Tutorial/Sequence.fs
samples/Tutorial/Todo.fsx
samples/Web/Startup.fs
src/Equinox.Core/Category.fs
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
src/Equinox/Core.fs
src/Equinox/Decider.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs
tools/Equinox.Tool/Program.fs

- Provides C#-friendly signatures equivalent to ones on `Decider`
- Align Esdb-like stores with others, renaming `BatchingPolicy` to `BatchOptions`, add `StoreContext` shortcut-constructor

V4 store alignment; DeciderCore

---

src/Equinox.Core/Category.fs

This flips the argument order from `context log cat` to `log cat context`
This makes it easier to switch from not using a context to using a context since the APIs are equivalent
```diff
- Category(....) |> Decider.resolve log
+ Category(....) |> Decider.resolveWithContext log
```

flip argument order for context taking functions putting the context last

---

src/Equinox.Core/Infrastructure.fs

See a comparioson of the ASM [here](https://sharplab.io/#v2:DYLgZgzgNALiCGEC2UAmIDUAfJB7VArsAKYAEAKgBYCWAdgOYCwAUCyTKQMaW64TEA1UgAowIUnQ4BaAHwTaHAG64ADjGq5aAShHwATnvGTS+vfACeOgLykA2llJhceiTGJJ5Jg6VS5SSeBhuR1d3UgB3ahhKUgF4YAJiAGVcJDJFUllSc2piYFRSDIc4hOIAOU0yLOEdLABdFjZiDhhcAHk1DVpSGzACWk51TVj4xJS0wsy5cfTSYtHyyqnSCtpiJo5uXn4BACYRMXlpOWNlTs1rUgBBAwsAOi2+MlFSGTlWjqHtIA=)
the new version doesn't need to allocate an option for each voption either.
Here's the result from a Benchmark.NET run as well
|     Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|----------- |---------:|---------:|---------:|-------:|----------:|
| ChooseVOld | 48.85 ns | 0.167 ns | 0.148 ns | 0.0162 |     136 B |
| ChooseVNew | 32.74 ns | 0.725 ns | 1.923 ns | 0.0076 |      64 B |
The old method allocates a …

Write out the loop for better perf on chooseV

---

src/Equinox.MessageDb/MessageDbClient.fs

I did some debugging and found that Npgsql loads the chunk in memory when doing `ExecuteReadAsync` so there's no reason to use the `ReadAsync` method. The behavior now mirrors what [Npgsql.Fsharp](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Npgsql.FSharp.fs#L455) does
Then I also noticed that a string was being allocated by npgsql for the data and meta fields so the getting of the field as a byte[] wasn't providing any benefit. I've made the change to UTF8 bytes explicit.
It also turns out that postgres can store nullable nulls 😂 
```sql
create table if not exists test (id int not null, json jsonb, primary key (id));
insert into test(id, json) values (1, null);
insert into test(id, json) values (2, 'null');
select * from test;
id | json
----+------
1 |
2 | null
(2 rows) …
```

MessageDB polish and fixes

---

src/Equinox.Core/Internal.fs
src/Equinox.MessageDb/Equinox.MessageDb.fsproj
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.MessageDb/Tracing.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs
tests/Equinox.MessageDb.Integration/Equinox.MessageDb.Integration.fsproj

I'm too used to tracing to not have it 😅 .
Wonder if we can compromise on this one and add tracing in an additive way like here.
There are three activities defined: 
- TrySync: when writing to a stream
- ReadBatch: when reading from a stream
- ReadSlice: child of read batch for each slice that's fetched
- ReadLast: Reading the last event of a stream
Screenshots of the integration tests

Add tracing to MessageDb module in an additive manner

---

src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.MessageDb/MessageDbClient.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs

Adds a baseline event size computation for the specified stores
Required for correct StreamsSink state logging when feeding from `EventStoreDbSource` https://github.com/jet/propulsion/pull/185

Esdb, Sss, Mdb: Implement ITimelineEvent.Size

---

README.md
samples/Store/Domain/Cart.fs
src/Equinox.Core/Infrastructure.fs
src/Equinox.MessageDb/Equinox.MessageDb.fsproj
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.MessageDb/MessageDbClient.fs
src/Equinox.MessageDb/Tracing.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs

As discussed, this is likely not worth the trouble.
I'm sharing it here anyway, I'm not sure whether this should ultimately be offered up as functionality of the messagedb store or not 🤔. I see the MessageDb store as a starting point that teams could eventually grow out of if their scale demands. It provides a decent set of trade-offs for medium throughput systems, and as such adding snapshots should in most cases be unnecessary.

add snapshotting to message-db

---

src/Equinox.Core/StopwatchInterval.fs
src/Equinox.MessageDb/Equinox.MessageDb.fsproj
src/Equinox.MessageDb/MessageDb.fs

It's here!
Let's use TaskSeq because it is new, shiny, and performant.
I've made no attempt to unroll anything into a while loop or that sort of stuff, just a pretty direct transform

MessageDb: Switch to TaskSeq

---

src/Equinox.DynamoStore/DynamoStore.fs

As a side effect of #361, `ProvisionedThroughputExceededExceptions` get nested:-
```
17:32:13 I Unhandled  {duration=00:00:00.3333882, events=9, stream="Loan-BC-I-00706146"}
System.AggregateException: One or more errors occurred. (One or more errors occurred. (The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.))
---> System.AggregateException: One or more errors occurred. (The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.)
---> Amazon.DynamoDBv2.Model.ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning …
```

Handle nested ProvisionedThroughputExceeded

---

samples/Infrastructure/Storage.fs
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.MessageDb/MessageDbClient.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs

Aligns MessageDb with DynamoStore and CosmosStore in using `Client` to refer to the layer that talks to the underlying store (but does not hold active connections as such)
- Having a Client similarly implies "make one of these and reuse them"
- However having an Establish or Connect method suggests that there is a long lived connection element and/or something interesting going on (for EventStore, Establish was originally a one-off Async method that did something)

MessageDb: Remove Connector

---

tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs

The repo contains a docker compose file that provisions a dynamodb-local instance
For the last batch of edits, I tested against a DynamoDB cloud instance
I erroneously updated the test expectations to match what I observed without considering that:
- I had tested against a cloud instance (the expectation is that the tests should just work from trunk).
- _dynamodb-local continues to have this behavioral difference_ (if you query with a maxItems that coincides with the number of items in the partition, you still get yielded a continuation token, which triggers an extra roundtrip)
This change makes the expectations of the integration tests suite conditional on the target instance URL, which is hacky. Hopefully this simulator difference goes away eventually...
resolves #366 (🙏 @nordfjord who …

DynamoDb: Fix integration test expectations

---

samples/Store/Domain/InventoryItem.fs
samples/Tutorial/Upload.fs
src/Equinox.Core/Category.fs
src/Equinox/StreamId.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

Provides an idiomatic C# equivalent for the FSharpFunc `StreamId.gen` (and shifts the type alias to Core now rather than having to do it at some other time)

StreamId C# interop

---

src/Equinox.DynamoStore/DynamoStore.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs

Add failing test when reading events from DynamoStore when not reading the batch containing the tip #376

DynamoDB: EventContext fails when tip not read

---

DOCUMENTATION.md
Equinox.sln
README.md
docker-compose-cosmos.sh
docker-compose-mssql.sh
docker-compose.yml
samples/Infrastructure/Storage.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs

Adds `docker compose` config for the CosmosDB emulator [for a Mac]

Cosmos: Add Docker emulator config

---

samples/Tutorial/Counter.fsx
src/Equinox.MemoryStore/MemoryStore.fs
tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs

Reverts the Committed event signature change, changing it from `string * string * Event[]' back to `FsCodecStreamName * Event[]`
The changed signature did not mesh well with the needs of test suites that use `Propulsion.Sinks` and/or `Propulsion.MemoryStore`
Also (temporarily) adds a hacked way to disable the locking. This will remain undocumented and will be removed in due course.

MemoryStore: Revert Committed event signature

---

docker-compose.yml
src/Equinox.Core/Infrastructure.fs
src/Equinox.Core/Internal.fs
src/Equinox.MessageDb/Equinox.MessageDb.fsproj
src/Equinox.MessageDb/MessageDb.fs
tests/Equinox.EventStore.Integration/StoreIntegration.fs

It's simply not justifiable to have a dependency on the library for this one little thing that doesn't benefit from it 😅

MessageDB: remove TaskSeq dep

---

CHANGELOG.md
src/Equinox.Core/Cache.fs
src/Equinox.Core/Caching.fs
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs

Spike - it could be this much shorter if we removed `ICache` ;) @DSilence

Remove ICache

---

CHANGELOG.md
src/Equinox.Core/Internal.fs
src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
src/Equinox.DynamoStore/Equinox.DynamoStore.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.EventStoreDb/Equinox.EventStoreDb.fsproj
src/Equinox.MessageDb/Equinox.MessageDb.fsproj
src/Equinox.SqlStreamStore/Equinox.SqlStreamStore.fsproj

- means we can remove shim versions of `takeWhile` etc in favor of the official version (0.4.0 release line)
- means `try`/`finally` and `use`/`use!` no longer leak (originally planned as 0.3.1, now rolled into 0.4.0)

Update TaskSeq to 0.4.0-alpha.1

---

CHANGELOG.md
README.md
diagrams/container.puml
src/Equinox.Core/AsyncCacheCell.fs
src/Equinox.Core/Cache.fs
src/Equinox.Core/Equinox.Core.fsproj
src/Equinox.Core/Infrastructure.fs
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
src/Equinox/Decider.fs
tests/Equinox.Core.Tests/AsyncBatchingGateTests.fs
tests/Equinox.Core.Tests/CachingTests.fs
tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs

Calved from #390
- Adds an `Async.call` helper, and cleans up some final straggler `Async` vs `Task` inconsistencies
- Includes some straggler cleanup and docs
- and lots of annoying test hardening; CI, xunit, sleeps and Task are a bad combo

Async cleanup

---

src/Equinox.MessageDb/MessageDbClient.fs

Noticed during my memory leak investigation in propulsion that using `@Variable` style Commands in Npgsql leads to `StringBuilder` allocations and all sorts of fun processing in the application that is avoidable by using `$1, $2` etc (the native format that pg parameterised queries take).
Secondly while scanning the code the queries looked a bit off with the `CorrelationId` and `CausationId` being picked from the json metadata. This makes sense if and only if we also place the id's onto these fields during writes. Since we don't this is just waste so 🧹  it

perf: use a literal for queries, and stop doing silly stuff with correlation/causation ids

---

src/Equinox.Core/Category.fs

Removes an ambiguity the F# compiler chokes on between the factory/extension methods module and the generic DeciderCore type which can require namespace `open`s we'd like to avoid forcing
Example: https://github.com/jet/propulsion/blob/90c843eaa495b440ad1a31223548eaf0f555f0c8/src/Propulsion.EventStore/Checkpoint.fs#L96-L97

Rename static DeciderCore -> Factory

---

src/Equinox.Core/Equinox.Core.fsproj
src/Equinox.DynamoStore/DynamoStore.fs
tests/Equinox.CosmosStore.Integration/AccessStrategies.fs

Handle nulls when unpacking Equinox.DynamoStore.Core.Token.isStale

Avoid null reference on cache read

---

README.md
src/Equinox.DynamoStore/DynamoStore.fs
tests/Equinox.CosmosStore.Integration/AccessStrategies.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs

Resolves #403; Adjusts the write algorithm to ensure all newly appended events are always first written to the tip (as opposed to potentially going straight to a calf batch as they do in the Cosmos impl, which would generally be more optimal both in RU cost and in density of events per Batch/Item in the store)
This is to enable downstream consumers of the DDB Streams (including `Propulsion.DynamoStore.Indexer`) to be guaranteed to see all appends for a given stream in the correct order.
----
Prompted by observations and analysis by @epNickColeman that writes to non-tip events (calved batches) were arriving out of order under non-trivial write load (previous load tests had not included triggering the calving of ). On closer investigation, the documentation for DDB Streams turns out to be …

DynamoStore: Feed all appends through tip

---

src/Equinox.MemoryStore/MemoryStore.fs

Removes a workaround before it becomes a misfeature that's going to cause pain to remove

fix(MemoryStore): Remove WithOrderingGuaranteesDisabled

---

CHANGELOG.md
src/Equinox/Decider.fs

The only usage I'm aware of has long gone
In general, optimising out roundtrips in ugly disconnected usage can be achieved by abuse of the read through cache facility, but feel free to discuss workarounds for usage here

feat!: Remove ISyncContext.CreateMemento

---

src/Equinox.Core/Caching.fs
src/Equinox.Core/Category.fs
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
tests/Equinox.Core.Tests/CachingTests.fs

Cleans up how the library guarantees that the edition of the Sync stored proc required by a given version of the library has been provisioned into the CosmosDB container in question
By @nordfjord

refactor(CosmosStore): Cleanup stored proc initialization

---

CHANGELOG.md
samples/Infrastructure/Services.fs
samples/Infrastructure/Store.fs
samples/Store/Integration/CartIntegration.fs
samples/Store/Integration/ContactPreferencesIntegration.fs
samples/Store/Integration/FavoritesIntegration.fs
samples/Tutorial/AsAt.fsx
samples/Tutorial/Cosmos.fsx
samples/Tutorial/FulfilmentCenter.fsx
samples/Tutorial/Gapless.fs
samples/Tutorial/Index.fs
samples/Tutorial/Sequence.fs
samples/Tutorial/Set.fs
samples/Tutorial/Todo.fsx
samples/Tutorial/Upload.fs
src/Equinox.Core/Cache.fs
src/Equinox.Core/Caching.fs
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
tests/Equinox.Core.Tests/CachingTests.fs
tests/Equinox.CosmosStore.Integration/AccessStrategies.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
tests/Equinox.EventStoreDb.Integration/StoreIntegration.fs

While the value of caching is most debatable for ESDB, in general forcing people to be explicit about their caching strategy is a nudge that's too important to give up
- It also makes the Cosmos and Dynamo implementations cleaner to follow
- Obviates the need for #399 (as Cosmos and Dynamo no longer need specific mapping of available strategies)
Following the logic to its conclusion, considering the Access Strategy should also not be considered a luxury for a non-top system.
- Adds an `Unoptimized` case for EventStore, EventStoreDb, MessageDb and SqlStreamStore 
HT @nordfjord for driving the suggestion

feat(Stores): Make caching and access mandatory

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

As per Dynamo's equivalent, provides an active pattern to identify relevant exception types with a view to classifying them in Propulsion handlers

feat(Cosmos): Add Exception pattern

---

samples/Infrastructure/Store.fs
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
tools/Equinox.Tool/Infrastructure/Infrastructure.fs

Includes minor cleanup work making logging consistent and/or aligning with equivalent in `dotnet-templates`

fix(Cosmos): add missing CosmosStoreContext.Connect wiring

---

CHANGELOG.md
samples/Infrastructure/Store.fs
src/Equinox.CosmosStore/CosmosStore.fs
tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
tools/Equinox.Tool/Infrastructure/Infrastructure.fs
tools/Equinox.Tool/Program.fs

Adds a `stats -A cosmos` option so nobody has to remember `-ESD` again

feat(Tool): eqx stats -A

---

Equinox.sln
README.md
docker-compose-mssql.sh
docker-compose.yml
tests/Equinox.EventStoreDb.Integration/StoreIntegration.fs

Applies the workaround suggested in https://github.com/microsoft/mssql-docker/issues/2#issuecomment-1683956282

chore(MsSql): Update MSSQL image workaround

---

CHANGELOG.md
src/Equinox.Core/Batching.fs

Adds a facility to the Batcher that (optionally) extends the Linger period to include a phase during which a `SemaphoreSlim` is acquired:
- the semaphore is `Release`d when the processing has finished
- further items can join the lingering batch during the acquisition period

feat(Batcher): Add Limiter option

---

CHANGELOG.md
DOCUMENTATION.md
samples/Store/Domain/Cart.fs
samples/Store/Domain/Favorites.fs
samples/Store/Domain/SavedForLater.fs
src/Equinox/Decider.fs
tests/Equinox.EventStoreDb.Integration/StoreIntegration.fs

Another run at #314
Having >10 overloads of transact has pros and cons; the seriousness of the cons is largely dependent on the IDE
While the single change I had to make to the consumption in this repo seems innocuous, IME it can be excruciating to resolve when you're just trying to make something work.
So I'm still not sure if it should actually be done...

fix!: Remove Async from TransactAsync, TransactExAsync

---

CHANGELOG.md
DOCUMENTATION.md
samples/Infrastructure/Services.fs
samples/Infrastructure/Store.fs
samples/Tutorial/AsAt.fsx
samples/Tutorial/Cosmos.fsx
samples/Tutorial/Counter.fsx
samples/Tutorial/Favorites.fsx
samples/Tutorial/FulfilmentCenter.fsx
samples/Tutorial/Todo.fsx
samples/Web/Startup.fs
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.DynamoStore/DynamoStore.fs
src/Equinox.EventStore/EventStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
src/Equinox.MemoryStore/MemoryStore.fs
src/Equinox.MessageDb/MessageDb.fs
src/Equinox.SqlStreamStore/SqlStreamStore.fs
src/Equinox.Tests/CachingTests.fs
src/Equinox/Caching.fs
src/Equinox/Category.fs
tests/Equinox.EventStoreDb.Integration/StoreIntegration.fs
tools/Equinox.Tool/Program.fs

Resolves #423
- `'context` -> `'req`
- 'Decider.forContext` -> `forRequest`
- `Store.Context` -> `Store.Config`

 refactor!: Label contexts unambiguously

---

CHANGELOG.md
DOCUMENTATION.md
README.md
docker-compose.yml
src/Equinox.CosmosStore/CosmosStore.fs
src/Equinox.EventStoreDb/EventStoreDb.fs
tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
tools/Equinox.Tool/Program.fs

`CosmosClientFactory` was hidden in `3.0.1` - this moves it to `Core` and removes a lot of redundancy
Prepares for a future implementation of [`TrustLocalEmulator=true` connection string value](#431 )

refactor(Cosmos)!: Cleanup CosmosClientFactory

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

Generalizes the compressUnfolds option (which defaults to `true`), to allow control at the specific Unfold event level.
Omitting continues to default to compressing (and not indexing) Unfolds.

feat(Cosmos): compressUnfolds -> shouldCompress

---

src/Equinox.CosmosStore/CosmosStore.fs
tools/Equinox.Tool/Program.fs

Preparatory refactoring in advance of #434
- `FromI` was always badly named
- `SyncExp` came later; there's definitely room to do more but the main goal here is to do 434 without inducing risk

refactor(Cosmos): SyncExp

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

Given the SDK supports a flag in the connection string, apps should stop leaning on this mechanism
See https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4222

feat(CosmosStore)!: Remove bypassCertificateValidation option

---

CHANGELOG.md
README.md
src/Equinox.Tests/CachingTests.fs
tools/Equinox.Tool/Program.fs

Adds features to `eqx query ... cosmos`:
- `-C`: emit query output to Console
- `-o/--output filepath`: emit CR-delimited JSON showing raw query output
- `-P`: pretty print the output indented over multiple lines
- `-m/--mode raw`: `SELECT *` from matching docs (and show ages)
- `-sn`: specify exact stream name instead of category name or category pattern
Example use cases:
- Useful complement to `eqx dump` for troubleshooting (`eqx query` focuses on the raw JSON and uses CosmosDB queries; `eqx dump` does a read Equivalent to an application-level `Query` call)
- Great for gathering event counts/RU cost stats for tuning/sanity checking
- Also useful for shuffling categories or streams between stores for inspection and/or doing general things that you do via `SELECT INTO` hackery in SQL …

feat(eqx query cosmos): Add -sn, -o, -P, -C, -m raw

---

CHANGELOG.md
README.md
samples/Infrastructure/Infrastructure.fsproj
samples/Store/Domain/Infrastructure.fs
samples/Web/Program.fs
samples/Web/Startup.fs
tools/Equinox.Tool/Infrastructure/Infrastructure.fs
tools/Equinox.Tool/Program.fs
tools/Equinox.Tool/StoreClient.fs
tools/Equinox.Tool/Tests.fs
tools/Equinox.Tool/TodoClient.fs

Aligns the Tool's commandline processing with that of Propulsion.Tool (i.e. more evolved patterns for commandline parsing)
- Minor tweaks re/ as a side-effect of https://github.com/fsprojects/Argu/issues/171
- rename the Tool's `run` Subcommand to the more 'say what you see' `loadTest`
- rename the mysterious-sounding `config` to `initSql` to align with `propulsion init`/`initAws` etc and https://github.com/jet/propulsion/pull/249
- minor polishing of CosmosQuery (follow-ups to #444) 
- re-ordering (no logic changes to stuff reordered other than `CosmosQuery`)
- move LoadTest logic to separate file, as it's not really part of the tool in any significant way
- change `eqx query` default format to `Raw` when writing to a `File` cia `-o`

refactor(Tool)!: run->loadTest, config->initSql

---

CHANGELOG.md
src/Equinox.CosmosStore.Prometheus/Equinox.CosmosStore.Prometheus.fsproj
src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
src/Equinox.DynamoStore.Prometheus/Equinox.DynamoStore.Prometheus.fsproj
src/Equinox.DynamoStore/Equinox.DynamoStore.fsproj
src/Equinox.EventStore/Equinox.EventStore.fsproj
src/Equinox.EventStoreDb/Equinox.EventStoreDb.fsproj
src/Equinox.MemoryStore/Equinox.MemoryStore.fsproj
src/Equinox.MessageDb/Equinox.MessageDb.fsproj
src/Equinox.SqlStreamStore.MsSql/Equinox.SqlStreamStore.MsSql.fsproj
src/Equinox.SqlStreamStore.MySql/Equinox.SqlStreamStore.MySql.fsproj
src/Equinox.SqlStreamStore.Postgres/Equinox.SqlStreamStore.Postgres.fsproj
src/Equinox.SqlStreamStore/Equinox.SqlStreamStore.fsproj

Adjusts internal dependencies to
- pin `Equinox.*Store` to depend on `Equinox [4.0.0, 5.0.0)`
- pin `Equinox.SqlStreamStore.*` to depend on `Equinox.SqlStreamStore [4.0.0, 5.0.0)`
This should mean:
- Equinox and library dependencies can be be independently updated
- The release of an Equinox v5 should not require any changes to the pinning at the app level

chore(Deps): Pin internal deps

---

CHANGELOG.md
src/Equinox/LazyTask.fs
tests/Equinox.Core.Tests/LazyTaskTests.fs

Where the request being processed via the read through cache mechanism gets `Cancelled` (via `CancellationTokenSource`, but also via things like `Async.Parallel`'s cancellation of sibling requests), the `Task` held within the `LazyTask` ends up in `Cancelled` state, not the more typical `IsFaulted`.
This leads to incorrect re-use of the cached value (as held within the cell).
This in turn leads to any request with `AnyCachedValue` (or `AllowStale`) in `4.0.0` failing with `TaskCancelledException` for as long as that cache entry lives.
----
While this is a relatively obvious mistake, the issue is only reproducable with very heavy parallism - and it's only in cache read through mode (`allowStale > TimeSpan.Zero`) that this comes into play.

fix(Caching): Correct Cancellation Handling

---

CHANGELOG.md
src/Equinox.Tests/CachingTests.fs
src/Equinox/Cache.fs

Fixes the condition for the swap, which has a race condition that can mean delivering the value we've just literally determined to be too old
Reduce a test timeout to hopefully reduce flakiness
Also fixes an oversight: even if a concurrent request was too old for the `maxAge`, it can still serve as the base state for an incremental load (not a big deal in the normal case; only the very first load would be suboptimal)

fix(Cache): Correct wait for concurrent request

---

CHANGELOG.md
README.md
src/Equinox.CosmosStore/CosmosStore.fs
tools/Equinox.Tool/Program.fs

- Add two new `eqx stats cosmos` queries
- remove `-A` flag (it's now on by default unless you specify >= 1)
- add top level `-Q` flag to omit timestamps/noise from output

feat(eqx stats): Oldest, Newest

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

Follow-up to #449
- Separate `Tip` operation from other `Read` activities
- Add min/max RU costs per operation
- Allow opt-in grouping of CosmosStore InternalMetrics by category
- Formatting improvements

feat(CosmosStore): Group metrics by Category, add min/max RU, tidy

---

CHANGELOG.md
src/Equinox.CosmosStore/CosmosStore.fs

Required for `propulsion sync` to be able to copy `u`nfold values too in https://github.com/jet/propulsion/pull/263

feat(Cosmos): Support ingesting unfolds

---

CHANGELOG.md
samples/Store/Domain.Tests/Domain.Tests.fsproj
samples/Store/Domain/Domain.fsproj
samples/Store/Integration/Integration.fsproj
samples/Tutorial/Tutorial.fsproj
samples/Web/Web.fsproj
src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
src/Equinox.Tests/Equinox.Tests.fsproj
tests/Equinox.Core.Tests/Equinox.Core.Tests.fsproj
tests/Equinox.CosmosStore.Integration/Equinox.CosmosStore.Integration.fsproj
tests/Equinox.DynamoStore.Integration/Equinox.DynamoStore.Integration.fsproj
tests/Equinox.EventStore.Integration/Equinox.EventStore.Integration.fsproj
tests/Equinox.EventStoreDb.Integration/Equinox.EventStoreDb.Integration.fsproj
tests/Equinox.MemoryStore.Integration/Equinox.MemoryStore.Integration.fsproj
tests/Equinox.MessageDb.Integration/Equinox.MessageDb.Integration.fsproj
tests/Equinox.SqlStreamStore.MsSql.Integration/Equinox.SqlStreamStore.MsSql.Integration.fsproj
tests/Equinox.SqlStreamStore.MySql.Integration/Equinox.SqlStreamStore.MySql.Integration.fsproj
tests/Equinox.SqlStreamStore.Postgres.Integration/Equinox.SqlStreamStore.Postgres.Integration.fsproj

In the previous round of STJ vulnernabilities, we updated min requirement to 8.0.4 to appease the scanner databases
Now dropping back down to the latest 6.x: 6.0.10 in the hope of the older version having less features and hence vuln-churn
- See also https://github.com/jet/FsCodec/releases/tag/3.0.3 (samples now ref same)
- Updated tests to net80 to match latest images (library packages don't yet have any net80 specific features)

fix(CosmosStore): Drop min STJ to 6.0.10

---

CHANGELOG.md
src/Equinox.MemoryStore/MemoryStore.fs

Simplified public TrySync method for direct usage in test scenarios

refactor(MemoryStore)!: remove unused TrySync args

---

CHANGELOG.md
README.md
tools/Equinox.Tool/CosmosStoreLinq.fs
tools/Equinox.Tool/Equinox.Tool.fsproj
tools/Equinox.Tool/Program.fs

- Adds `eqx top`, which summarizes categories and/or stream stats (see README for examples)
- Adds `eqx destroy`, supporting deleting streams (and/or categories thereof) from an Equinox store
- `eqx dump`: Applies a bare mode when in `-Q`uiet mode
- Various improvements to eqx tool outputs and cleanups of flags

feat(eqx): Add top, destroy, -Q, -sl etc
