jet/equinox

- build.ps1
- cli/Equinox.Cli/Program.fs
- src/Equinox.Cosmos/Cosmos.fs
- src/Equinox.EventStore/Infrastructure.fs
- tests/Equinox.Cosmos.Integration/CacheCellTests.fs
- tests/Equinox.Cosmos.Integration/Equinox.Cosmos.Integration.fsproj
This implements #59, which will make it safer/easier for consumers to update their `Equinox.Cosmos` package. Provisos mentioned on that Issue apply as to whether the whole thing is a good idea of course (arguably, especially having it on by default)
> Cosmos: Auto-provision stored procedure

- CHANGELOG.md
- DOCUMENTATION.md
- Equinox.sln
- README.md
- build.proj
- samples/Tutorial/Counter.fsx
- samples/Tutorial/Favorites.fsx
- samples/Tutorial/Todo.fsx
- samples/Tutorial/Tutorial.fsproj
Addresses #56 - comments are more than welcome
> Add Commands and Handlers Tutorial

- CHANGELOG.md
- src/Equinox.Projection/Equinox.Projection.fsproj
- src/Equinox.Projection/Infrastructure.fs
- src/Equinox.Projection/Projection.fs
- src/Equinox.Projection/State.fs
- tests/Equinox.Projection.Tests/Equinox.Projection.Tests.fsproj
- tests/Equinox.Projection.Tests/ProgressTests.fs
- tests/Equinox.Projection.Tests/StreamStateTests.fs
Split from https://github.com/jet/dotnet-templates/pull/16
> Projection State / Pipeline + Tests

- CHANGELOG.md
- src/Equinox.Projection/Equinox.Projection.fsproj
- src/Equinox.Projection/Infrastructure.fs
- src/Equinox.Projection/Projection.fs
- tests/Equinox.Projection.Tests/StreamStateTests.fs
This code is extracted from jet/dotnet-templates#16 and addresses the following concerns:
- optimization work resulting from load testing
- separating out interfaces to enable forks of individual components
- remove `System.ValueType` dependency (it may return but we've yet to do significant profiling--driven tuning as yet)
> Projection Optimization + Interfaces

- CHANGELOG.md
- src/Equinox.Cosmos/Cosmos.fs
- src/Equinox.EventStore/EventStore.fs
- src/Equinox.MemoryStore/MemoryStore.fs
- src/Equinox/Stream.fs
Less pejorative term for low level control of Stream Name, see #147 for discussion of tradeoffs
> DeprecatedRawName -> StreamName re #147

- samples/Tutorial/FulfilmentCenter.fsx
- samples/Tutorial/Tutorial.fsproj
Will merge this as a Tutorial script representative of a trivial but real aggregate when I cross check it with an actual impl @jgardella
> Add Fulfilment Center example

- CHANGELOG.md
- README.md
- tools/Equinox.Tool/Infrastructure/Infrastructure.fs
- tools/Equinox.Tool/Program.fs
No, it aint pretty ;)
Closes #127
> Implement stats subcommand #127

- CHANGELOG.md
- src/Equinox.EventStore/EventStore.fs
Resolves #185, see issue description
> Fix #185: Add EventStore Connector missing configuration for ClientConnectionTimeout and GossipTimeout

- .editorconfig
- DOCUMENTATION.md
- src/Equinox.Core/AsyncCacheCell.fs
- src/Equinox.Core/Cache.fs
- src/Equinox.Core/Infrastructure.fs
- src/Equinox.Core/Retry.fs
- src/Equinox.Core/Stream.fs
- src/Equinox.Core/Types.fs
- src/Equinox.EventStore/EventStore.fs
- src/Equinox/Equinox.fs
- src/Equinox/Flow.fs
Pretty much more of the same as https://github.com/jet/FsCodec/pull/32
The ES Tests still run and succeed
> minor style changes

- samples/Infrastructure/Storage.fs
- samples/Store/Integration/CartIntegration.fs
- samples/Store/Integration/ContactPreferencesIntegration.fs
- samples/Store/Integration/FavoritesIntegration.fs
- src/Equinox.Cosmos/Cosmos.fs
- src/Equinox.Cosmos/CosmosJsonSerializer.fs
- tests/Equinox.Cosmos.Integration/CosmosFixtures.fs
- tests/Equinox.Cosmos.Integration/CosmosIntegration.fs
- tools/Equinox.Tool/Program.fs
re #197 #203 Random changes as I review the code
> Cosmos SDK 4 code review / cleanup

- DOCUMENTATION.md
I hadn't reviewed the glossary much in recent times; this is much needed now as the Equinox and Propulsion docs and diagrams are both written in terms of definitions in it.
The main goal here is to align with terms and concepts used in https://github.com/jet/propulsion/blob/diag/DOCUMENTATION.md#overview
Best reviewed by reading: https://github.com/jet/equinox/blob/diag/DOCUMENTATION.md#glossary
> Major glossary update

- CHANGELOG.md
- samples/Store/Backend/Favorites.fs
- samples/Store/Integration/CartIntegration.fs
- samples/Store/Integration/ContactPreferencesIntegration.fs
- samples/Store/Integration/FavoritesIntegration.fs
- samples/Tutorial/Counter.fsx
- samples/Tutorial/Favorites.fsx
- src/Equinox.MemoryStore/MemoryStore.fs
- tests/Equinox.MemoryStore.Integration/MemoryStoreIntegration.fs
Resolves #205 by providing a `Committed` event on `MemoryStore.VolatileStore`
> Add MemoryStore ChangeFeed re #205

- README.md
Update README.MD to show FsCodec.SystemTextJson as released (not planned)
> Update README.MD to show FsCodec.SystemTextJson

- CHANGELOG.md
- samples/Store/Integration/LogIntegration.fs
- src/Equinox.Cosmos/Cosmos.fs
- tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
- tests/Equinox.Cosmos.Integration/CosmosFixturesInfrastructure.fs
- tools/Equinox.Tool/Equinox.Tool.fsproj
- tools/Equinox.Tool/Program.fs
> Cosmos: Add Prune API

- CHANGELOG.md
- src/Equinox.CosmosStore/CosmosStore.fs
- tools/Equinox.Tool/Program.fs
> Update `eqx init` to support Serverless re #244

- CHANGELOG.md
- Equinox.sln
- build.proj
- samples/Store/Integration/LogIntegration.fs
- samples/Tutorial/Counter.fsx
- src/Equinox.Cosmos.Prometheus/CosmosPrometheus.fs
- src/Equinox.Cosmos.Prometheus/Equinox.Cosmos.Prometheus.fsproj
- src/Equinox.Cosmos/Cosmos.fs
- tests/Equinox.Cosmos.Integration/CosmosCoreIntegration.fs
- tests/Equinox.Cosmos.Integration/CosmosFixturesInfrastructure.fs
> Cosmos.Prometheus Backport from master #266

- CHANGELOG.md
- src/Equinox.MemoryStore/MemoryStore.fs
Resolves #265 using technique described in #264
> MemoryStore: Serialize Committed events re #265

- CHANGELOG.md
- src/Equinox.MemoryStore/MemoryStore.fs
> MemoryStore: Serialize Committed events as v2 #268

- CHANGELOG.md
- src/Equinox.CosmosStore/CosmosStore.fs
- src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
> Cosmos: Use 3.13; Dispose FeedResponse fixes #225

- CHANGELOG.md
- samples/Infrastructure/Storage.fs
- tests/Equinox.CosmosStore.Integration/Equinox.CosmosStore.Integration.fsproj
- tools/Equinox.Tool/Equinox.Tool.fsproj
> Equinox.Tool: Fix incorrect Azure.Cosmos.Direct ref

- Equinox.sln.DotSettings
- samples/Tutorial/AsAt.fsx
- samples/Tutorial/Cosmos.fsx
- samples/Tutorial/Counter.fsx
- samples/Tutorial/Favorites.fsx
- samples/Tutorial/FulfilmentCenter.fsx
- samples/Tutorial/Gapless.fs
- samples/Tutorial/Index.fs
- samples/Tutorial/Sequence.fs
- samples/Tutorial/Set.fs
- samples/Tutorial/Todo.fsx
- samples/Tutorial/Tutorial.fsproj
- samples/Tutorial/Upload.fs
After far too long, completing #262 by @voronoipotato
> Update Tutorial fsx files to use #r nuget references

- CHANGELOG.md
- src/Equinox.CosmosStore/CosmosStore.fs
Discovered in the course of implementing #321
Resolves #322
> Fix Multi-Unfolds Index numbers

- CHANGELOG.md
- samples/Store/Domain/Favorites.fs
- samples/Store/Domain/SavedForLater.fs
- samples/TodoBackend/Todo.fs
- samples/Tutorial/Counter.fsx
- samples/Tutorial/Favorites.fsx
- samples/Tutorial/FulfilmentCenter.fsx
- samples/Tutorial/Todo.fsx
- src/Equinox/Decider.fs
- tests/Equinox.CosmosStore.Integration/AccessStrategies.fs
Some relatively low usage overloads from the field. Some may be removed or tweaked before final V4 release.
> Add Transact overloads

- CHANGELOG.md
- samples/Store/Domain/Cart.fs
- samples/Store/Domain/Favorites.fs
- samples/Store/Domain/SavedForLater.fs
- src/Equinox/Decider.fs
Supersedes #320 and #314 as they didn't deliver a good intellisense/compiler error experience
> Fix Transact overloads experience

- src/Equinox.CosmosStore/CosmosStore.fs
- src/Equinox.DynamoStore/DynamoStore.fs
- src/Equinox.MemoryStore/MemoryStore.fs
- src/Equinox/Core.fs
- src/Equinox/Decider.fs
- tests/Equinox.CosmosStore.Integration/CosmosFixturesInfrastructure.fs
- tests/Equinox.EventStore.Integration/Infrastructure.fs
- tools/Equinox.Tool/Program.fs
Replaces closure with arg overload of ConcurrentDictionary.AddOrUpdate
> MemoryStore perf/cleanup

- src/Equinox.DynamoStore/DynamoStore.fs
- src/Equinox.DynamoStore/Equinox.DynamoStore.fsproj
- tools/Equinox.Tool/Program.fs
As part of https://github.com/jet/propulsion/pull/143, the stream ARN needs to be supplied
> Surface Streams ARN from eqx initaws

- README.md
- samples/Infrastructure/Storage.fs
- src/Equinox.DynamoStore/DynamoStore.fs
- tools/Equinox.Tool/Program.fs
Affords a way to inspect the streaming configuration (and throughput config) for a store from the CLI
> Add eqx stats dynamo

- src/Equinox.MessageDb/MessageDb.fs
- tests/Equinox.EventStore.Integration/StoreIntegration.fs
> Make MessageDB versions 0-based rather than -1 based

- azure-pipelines.yml
- tests/Equinox.EventStore.Integration/StoreIntegration.fs
I'm not quite sure how to test if this works on my own 😓
> attempt to run message-db integration in CI

- src/Equinox.MessageDb/Equinox.MessageDb.fsproj
Npgsql has released v7, so let's get up to date in MessageDB
> Upgrade Npgsql to v7 now that it's GA

- README.md
- docker-compose-cosmos.sh
- docker-compose.yml
- src/Equinox.CosmosStore/CosmosStore.fs
- src/Equinox/Decider.fs
- src/Equinox/Stream.fs
- tests/Equinox.CosmosStore.Integration/AccessStrategies.fs
- tests/Equinox.CosmosStore.Integration/CosmosCoreIntegration.fs
- tests/Equinox.CosmosStore.Integration/CosmosFixtures.fs
- tools/Equinox.Tool/Program.fs
Made 2 stupid slips, which were trapped by the tests 😊
Some code clarifications from the debugging process retained
Fixes `fallback` test (wiring of test was broken during recent connection logic refactoring)
> fix(Cosmos): Fix #438, prep #434

- samples/Store/Domain/ContactPreferences.fs
- src/Equinox.MessageDb/MessageDb.fs
- src/Equinox.MessageDb/MessageDbClient.fs
- tests/Equinox.MessageDb.Integration/AdjacentProjection.fs
- tests/Equinox.MessageDb.Integration/Equinox.MessageDb.Integration.fsproj
- tests/Equinox.MessageDb.Integration/OnSync.fs
Based on the work in https://github.com/equinox-project/equinox-js/pull/70
You can nit my formatting all you want, this is just checking the feasibility of the approach in F#
> feat(MessageDb): Support triggers `onSync`

- Equinox.sln.DotSettings
- global.json
- samples/Store/Domain.Tests/SavedForLaterTests.fs
- samples/Store/Domain/Cart.fs
- samples/Store/Domain/ContactPreferences.fs
- samples/Store/Domain/Favorites.fs
- samples/Store/Domain/SavedForLater.fs
- samples/Store/Integration/TestOutput.fs
- samples/Tutorial/AsAt.fsx
- samples/Tutorial/Cosmos.fsx
- samples/Tutorial/Counter.fsx
- samples/Tutorial/Favorites.fsx
- samples/Tutorial/FulfilmentCenter.fsx
- samples/Tutorial/Gapless.fs
- samples/Tutorial/Todo.fsx
- src/Equinox.CosmosStore/CosmosStore.fs
- src/Equinox.DynamoStore/DynamoStore.fs
- src/Equinox.EventStore/EventStore.fs
- src/Equinox.EventStoreDb/Equinox.EventStoreDb.fsproj
- src/Equinox.EventStoreDb/EventStoreDb.fs
- src/Equinox.MessageDb/MessageDb.fs
- src/Equinox.MessageDb/MessageDbClient.fs
- src/Equinox.SqlStreamStore/SqlStreamStore.fs
- src/Equinox/Category.fs
- src/Equinox/Equinox.fsproj
- tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
- tools/Equinox.Tools.TestHarness/Aggregate.fs
Seems a bit underwhelming compared to app code...
> chore: LangVersion 8

- tests/Equinox.CosmosStore.Integration/DocumentStoreIntegration.fs
> chore: add a test to specify the expectation when moving between access strategies

- CHANGELOG.md
- src/Equinox.CosmosStore/CosmosStore.fs
- src/Equinox.DynamoStore/DynamoStore.fs
Brings the per-table grouping from Dynamo to group Cosmos by Container
> feat(Cosmos InternalMetrics): Group by Container

- src/Equinox.Core/Equinox.Core.fsproj
- src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
- src/Equinox.DynamoStore/Equinox.DynamoStore.fsproj
- src/Equinox.EventStore/Equinox.EventStore.fsproj
- src/Equinox.EventStoreDb/Equinox.EventStoreDb.fsproj
- src/Equinox.MemoryStore/Equinox.MemoryStore.fsproj
- src/Equinox.MessageDb/Equinox.MessageDb.fsproj
- src/Equinox.SqlStreamStore.MsSql/Equinox.SqlStreamStore.MsSql.fsproj
- src/Equinox.SqlStreamStore.MySql/Equinox.SqlStreamStore.MySql.fsproj
- src/Equinox.SqlStreamStore.Postgres/Equinox.SqlStreamStore.Postgres.fsproj
- src/Equinox.SqlStreamStore/Equinox.SqlStreamStore.fsproj
- src/Equinox/Equinox.fsproj
- tools/Equinox.Tools.TestHarness/Equinox.Tools.TestHarness.fsproj
TIL https://devblogs.microsoft.com/dotnet/package-validation/#validation-against-baseline-package-version thanks to https://github.com/fsprojects/FsHttp/issues/194#issuecomment-2094703295
> chore: Add Package Validation

- CHANGELOG.md
- src/Equinox.CosmosStore/Equinox.CosmosStore.fsproj
See https://github.com/jet/FsCodec/pull/122
> chore(deps, Cosmos): Up min STJ version to 8.0.4

- samples/Tutorial/Counter.fsx
Removes usage of the Command pattern - while most event sourcing 101s use it as the goto example (and Equinox itself is, as the initial example showed, perfectly fine with the pattern), over time I've found that trying to use that as the dominant pattern constrains one's thinking for some of the following reasons:
- if one decision yields a result (be it a status, a projection from the result, etc), then all commands must fit that same signature. This often means you end up with a 'lowest common multiple' type, which you then use comments to note as only applying to some commands
- there is nothing simpler to test than a decision function that takes only 1. relevant parameters 2. the state
- a decision sometimes involves looking at the state, doing something (copying, merging it with some …
> refactor(Counter sample): Remove Command pattern
